APPLICATION = spotify_matrix

BOARD ?= esp32-wroom-32

RIOTBASE ?= $(CURDIR)/../../RIOT

# Features required
FEATURES_REQUIRED += cpp # basic C++ support
FEATURES_REQUIRED += libstdcpp # libstdc++ support (for #include <cstdio>)

CXXEXFLAGS +=

include $(RIOTBASE)/Makefile.include